version: "3.7"
services:
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - database-data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
    ports:
      - 4005:4005
    external_links:
      - database
    depends_on:
      - database

  app:
    container_name: app
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NEXT_PUBLIC_CARS_API=${NEXT_PUBLIC_CARS_API}
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  database-data:
    driver: local
